services:
  zecretly_test_db:
    container_name: zecretly-test-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=zecretly_test
      - POSTGRES_PASSWORD=zecretly_test_password
      - POSTGRES_DB=zecretly_test
      - POSTGRES_INITDB_ARGS=--auth-local=trust --auth-host=md5
    ports:
      - "5434:5432"  # Different port to avoid conflicts with main db
    volumes:
      - zecretly_test_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zecretly_test -d zecretly_test"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - zecretly_test

volumes:
  zecretly_test_pg_data:
    driver: local

networks:
  zecretly_test:
    driver: bridge
