/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DocsImport } from './routes/docs'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FeaturesIndexImport } from './routes/features/index'
import { Route as FeaturesApiTestingImport } from './routes/features/api-testing'

// Create/Update Routes

const DocsRoute = DocsImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesIndexRoute = FeaturesIndexImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesApiTestingRoute = FeaturesApiTestingImport.update({
  id: '/features/api-testing',
  path: '/features/api-testing',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsImport
      parentRoute: typeof rootRoute
    }
    '/features/api-testing': {
      id: '/features/api-testing'
      path: '/features/api-testing'
      fullPath: '/features/api-testing'
      preLoaderRoute: typeof FeaturesApiTestingImport
      parentRoute: typeof rootRoute
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/features/api-testing': typeof FeaturesApiTestingRoute
  '/features': typeof FeaturesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/features/api-testing': typeof FeaturesApiTestingRoute
  '/features': typeof FeaturesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/docs': typeof DocsRoute
  '/features/api-testing': typeof FeaturesApiTestingRoute
  '/features/': typeof FeaturesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/docs' | '/features/api-testing' | '/features'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/docs' | '/features/api-testing' | '/features'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/docs'
    | '/features/api-testing'
    | '/features/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DocsRoute: typeof DocsRoute
  FeaturesApiTestingRoute: typeof FeaturesApiTestingRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DocsRoute: DocsRoute,
  FeaturesApiTestingRoute: FeaturesApiTestingRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/docs",
        "/features/api-testing",
        "/features/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/docs": {
      "filePath": "docs.tsx"
    },
    "/features/api-testing": {
      "filePath": "features/api-testing.tsx"
    },
    "/features/": {
      "filePath": "features/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
